# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create libs directory
      run: mkdir -p libs
    - name: Download external JAR
      run: curl -L -o libs/2DBoardGameFrame-0.2.3-Alpha.jar https://github.com/Fros1er/2DBoardGameFrame/releases/download/v0.2.3-alpha/2DBoardGameFrame-0.2.3-Alpha.jar
    - name: Install external JAR
      run: mvn install:install-file -Dfile=libs/2DBoardGameFrame-0.2.3-Alpha.jar -DgroupId=com.froster -DartifactId=2DBoardGameFrame -Dversion=0.2.3 -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
